### ISSUE TITLE
What are the advantages of authenticating using the payload rather than request header?

### ISSUE THREAD

**Issue by iteles** [dwyl/hapi-login#1]
What are the advantages of authenticating using a POST payload vs the request header as [hapi-auth-basic](https://github.com/hapijs/hapi-auth-basic/) goes?

**Comment by nelsonic** [comment]
Glad you asked! :wink: 
I hope to answer this shortly in the Readme...

**Comment by nelsonic** [comment]
@iteles can you please confirm if the README answers your question?

**Comment by iteles** [comment]
Oops, yes, definitely closed! Thanks!
