### ISSUE TITLE
Comment about not leaking info about user existence

### ISSUE THREAD

**Issue by FullStackForger** [dwyl/hapi-login#14]
It is more question or suggestion more than a question.

In the README.md section: [Example handler function](https://github.com/dwyl/hapi-login/blob/master/README.md#3-define-your-custom-handler-function), there is a comment warning about not leaking user existence. 

```
db.get(request.payload.email, function(err, res) {

  if(err) {
      reply('fail').code(400); // don't leak info about user existence
    }
  })
```

Small thing but if possible I would suggest we modify it. Isn't it good practice to actually tell user why he/she can not register the account. Perhaps we could throw forbidden error, like so:

```
db.get(request.payload.email, function(err, res) {

  if(err) {
      // reply with 403 error code
      reply(Boom.forbidden('There is an account associated with this email.')); 
    }
  })
```

Any thoughts?

**Comment by nelsonic** [comment]
@indieforger _really_ good question! 😉 
The "_best practice_" is actually:

``` js
reply(Boom.notFound('Sorry, that username or password is invalid, please try again.'));
```

e.g:
![github-login-error-wrong-password](https://cloud.githubusercontent.com/assets/194400/14589237/109546d4-04d5-11e6-954a-85230f7e9b78.png)

See: OWASP Auth for list of responses which "_Leak information_": 
https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Incorrect_Response_Examples
and UX copywriting: 
http://ux.stackexchange.com/questions/5291/why-is-the-common-practice-of-sign-in-error-message-always-mix-the-wrong-usernam

**Comment by nelsonic** [comment]
@indieforger if you have time, please PR the change. thanks! 👍

**Comment by FullStackForger** [comment]
Great! Will do!
