### ISSUE TITLE
Should we Extend the register example to include login or should it be separate?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-login#4]
Should we _expand_ on https://github.com/dwyl/hapi-register-example/ or write a diff example?

**Comment by iteles** [comment]
I think it would be helpful to have an example _for each_ module so there people are aware they can use them individually.

**Comment by nelsonic** [comment]
Right... except that we don't (_really_) _expect_ people to use `/login` **_without**_ `/register`
They are separate for testability reasons... but they will both be used in https://github.com/dwyl/hapi-login where most people will experience them...

**Comment by iteles** [comment]
I actually think it makes sense to just have a hapi-login example. That will be without a doubt the most useful use of time.

**Comment by nelsonic** [comment]
Done: https://github.com/nelsonic/hapi-login-example

<img width="432" alt="hapi-login-page" src="https://cloud.githubusercontent.com/assets/194400/10523082/6e7fab3c-7370-11e5-91e2-639fc725b3e6.png">
