### ISSUE TITLE
Glue usage

### ISSUE THREAD

**Issue by vdeturckheim** [dwyl/hapi-login#9]
Hi,

I have been looking at the repo and I'm under the impression it would not easily go on with [Glue](https://github.com/hapijs/glue) because of the use of Joi templates for custom fields. 

Am I missing something ?  Right now I would say you need to define a custom hapi plugin calling hapi-login (and configuring it) and then register this custom plugin from the Glue manifest. 

Sorry if I'm raising a false issue ^^
Vlad.

**Comment by nelsonic** [comment]
@vdeturckheim you're absolutely right. The [Joi](https://github.com/hapijs/joi) field validation will prevent usage of `glue`. 
Are you _currently_ using `glue` for your projects...?
We can re-work this module to support glue. However our other plugins e.g: [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) (_the most popular auth plugin on NPM_) requires a function in the configuration object. this is non-standard JSON and therefore cannot be in a `manifest.json` file.

**Comment by nelsonic** [comment]
Relates to: https://github.com/dwyl/learn-hapi/issues/44

**Comment by vdeturckheim** [comment]
@nelsonic thanks for the answer! 
Actually I was just curious if there were any better way to go than the 'custom plugin wrapping' I'm using right now. I'm starting to think that regarding the auth topic it is the only solution (except, maybe enforcing a stong convention regarding plugins' behavior but it's still foggy in my mind).

Regarding my usage of `glue`, I'm moving my answer in [the other feed](https://github.com/dwyl/learn-hapi/issues/44).

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/learn-hapi/issues/44
